os: linux
dist: xenial
language: ruby
cache: bundler

services:
  - redis

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - virtualstaticvoid@gmail.com
    on_failure: change
    on_success: never

