language: ruby
sudo: false  # See http://docs.travis-ci.com/user/migrating-from-legacy
cache: bundler

services:
  - redis-server

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - virtualstaticvoid@gmail.com
    on_failure: change
    on_success: never

