language: ruby
sudo: false  # See http://docs.travis-ci.com/user/migrating-from-legacy
cache: bundler

services:
  - redis-server

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - virtualstaticvoid@gmail.com
    on_failure: change
    on_success: never

